# For documentation, see https://golangci-lint.run/usage/configuration/

linters:
  enable:
    - unconvert
    - unparam
    - gofmt
  disable:
    - typecheck
linters-settings:
  errcheck:
    exclude-functions:
      - (*log.Logger).Output
