before:
  hooks:
    - go mod tidy
    - go test -tags=unit ./...
    # call generate manually to not slow down release: https://github.com/golang/go/issues/49039
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    id: corp-net-indicator
    main: ./main.go
    buildmode: pie
    ldflags:
      - -s -w -X com.telekom-mms.corp-net-indicator/internal/config.Version={{.Version}} -X com.telekom-mms.corp-net-indicator/internal/config.Commit={{.Commit}}
    hooks:
      post:
        - '/usr/bin/bash -c "set -ex; /usr/bin/upx dist/corp*/corp*"'
archives:
  - format: tar.gz
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - package_name: corp-net-indicator
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    vendor: Deutsche Telekom MMS GmbH
    maintainer: The MMS Linux Dev Team <mmslinux-dev@telekom.de>
    description: |-
      Corporate Network Status
      Program to show network status and controls identity login and vpn connection.
    license: MIT
    formats:
      - deb
    # dependencies:
    #   - "fw-id-agent"
    #   - "oc-daemon"
    bindir: /usr/bin
    section: net
    priority: optional
    # currently buggy -> ignores in lintian-overrides
    # chglog init -> generates changelog.yml
    # chglog add --version v#.#.# -> after every tag, call in hook above?
    # changelog: "changelog.yml"
    dependencies:
      - "libc6"
      - "libcairo-gobject"
      - "libcairo"
      - "libgdk-pixbuf-2.0"
      - "libgio-2.0"
      - "libglib-2.0"
      - "libgobject-2.0"
      - "libgraphene-1.0"
      - "libgtk-4"
      - "libpango-1.0"
    contents:
      - src: init/corp-net-indicator.desktop
        dst: /etc/xdg/autostart/
        type: config
      - src: copyright
        dst: /usr/share/doc/corp-net-indicator/
        file_info:
          mode: 0644
      - src: lintian-overrides
        dst: ./usr/share/lintian/overrides/corp-net-indicator
        packager: deb
        file_info:
          mode: 0644
release:
  prerelease: auto
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
