name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          # https://github.com/golangci/golangci-lint-action/issues/135
          skip-pkg-cache: true
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Install xvfb, upx and gtk
        run: sudo apt-get update && sudo apt-get install upx-ucl libgtk-4-dev  libglib2.0-dev xvfb -y

      - name: Run test
        run: xvfb-run -a go test -v -timeout 60m -coverprofile cover.out ./... | tee test.out && exit ${PIPESTATUS[0]}

      - name: Process results
        if: always()
        uses: malaupa/go-test-coverage-summary-action@v0.0.10
        with:
          with_archive: true
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
