name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Tags
        run: git fetch --force --tags

      - name: Install dbus and upx
        run: sudo apt-get update && sudo apt-get install dbus dbus-x11 upx-ucl libgtk-4-dev

      - name: Setup Go
        # uses: magnetikonline/action-golang-cache@v4
        # with:
        #   go-version: stable
        #   cache-key-suffix: ci
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
